# https://github.com/rust-lang-nursery/rustfmt
# https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md
# required stable version rustfmt 1.4.12-stable (a828ffea 2020-03-11)

edition = "2018"
use_field_init_shorthand = true
reorder_imports = false
reorder_modules = false
merge_derives = true
newline_style = "Unix"
use_small_heuristics = "Default"
#! indent_style = "Visual"
fn_args_layout = "Tall"
